title: Red Origen
description: Cooperativa de trabajo para terapias cannábicas
author: ORIGEN Cooperativa de Trabajo LTD.
baseurl: "" # Dejar vacío si es en la raíz
url: "https://redorigen.com.ar"
theme: 
collections:
  terapias:
    output: true
    permalink: /:name/